#!/usr/bin/sh

NVIM_MINIMALIST=~/.config/nvim-minimalist
export NVIM_MINIMALIST

alias nvmm='XDG_DATA_HOME=$NVIM_MINIMALIST/share XDG_CACHE_HOME=$NVIM_MINIMALIST XDG_CONFIG_HOME=$NVIM_MINIMALIST nvim'

nvmm
